// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

namespace WebApp.Migrations
{
    [DbContext(typeof(FuelCartDBContext))]
    [Migration("20190403193457_modifyRegisterHead")]
    partial class modifyRegisterHead
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApp.Models.FuelCartModel", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartName");

                    b.Property<int?>("HeadTypeId");

                    b.HasKey("CartId");

                    b.HasIndex("HeadTypeId");

                    b.ToTable("FuelCarts");
                });

            modelBuilder.Entity("WebApp.Models.RegisterHead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("RegisterHead");
                });

            modelBuilder.Entity("WebApp.Models.FuelCartModel", b =>
                {
                    b.HasOne("WebApp.Models.RegisterHead", "HeadType")
                        .WithMany()
                        .HasForeignKey("HeadTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
